[project]
name = "tightwrap"
version = "24.1.0"
description = "A typed `functools.wraps`."
authors = [
    {name = "Tin Tvrtković", email = "tinchester@gmail.com"},
]
dependencies = ["typing_extensions; python_version < '3.10'"]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "Apache2"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pdm]
package-type = "library"

[tool.pdm.dev-dependencies]
lint = [
    "mypy>=1.8.0",
    "ruff>=0.1.11",
]
test = [
    "pytest>=7.4.4",
    "coverage>=7.4.0",
]

[tool.coverage.run]
parallel = true
source_pkgs = ["tightwrap"]